name: SampleApp
options:
  xcodeVersion: "12.0"
  deploymentTarget:
    iOS:  "14.0"
  developmentLanguage: en
  bundleIdPrefix: com.github.droibit

settings:
  base:
    SWIFT_VERSION: 5.0

targets:
  SampleApp:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: SwiftUI-DI
        PRODUCT_BUNDLE_IDENTIFIER: com.github.droibit.sample.${PRODUCT_NAME}
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: "\"Sources/Resources/Preview Content\""
    sources:
      - path: Sources
      - path: Sources/DI/NeedleGenerated.swift
        optional: true
        createIntermediateGroups: true
    dependencies:
      - carthage: NeedleFoundation
      - carthage: RxSwift
      - carthage: RxRelay
    preBuildScripts:      
      - name: Run needle
        path: /bin/sh
        outputFiles:
          - $SRCROOT/Sources/DI/NeedleGenerated.swift
        script: export SOURCEKIT_LOGGING=0 && Carthage/Checkouts/needle/Generator/bin/needle generate Sources/DI/NeedleGenerated.swift Sources/

schemes:
  SampleApp:
    build:
      targets:
        SampleApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile: 
      config: Debug
    analyze:
      config: Debug
    archive: 
      config: Debug      